// Copyright 2021 Google Inc. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using NHibernate.Mapping.ByCode;
using NHibernate.Mapping.ByCode.Conformist;
using System;

namespace Google.Cloud.Spanner.NHibernate.Samples.SampleModel
{
    /// <summary>
    /// Abstract base class for all sample entities.
    ///
    /// All these entities use a client side generated GUID that is stored as a string as the primary key.
    /// The base entity also has a Version property that is used for optimistic locking and concurrency checking by
    /// NHibernate, and a CreatedAt and LastUpdatedAt property that indicate when an entity instance was initially
    /// created and when it was last updated. These properties are automatically assigned the commit timestamp of the
    /// transaction that created or last updated the entity.
    /// </summary>
    public abstract class AbstractVersionedEntity
    {
        /// <summary>
        /// The primary key is a client-side generated UUID. Cloud Spanner does not support any server side key
        /// generation. The key value must therefore be set or generated client side. Monotonically increasing
        /// values are NOT recommended for PRIMARY KEYs.
        /// See also: https://cloud.google.com/spanner/docs/schema-and-data-model#choosing_a_primary_key
        /// </summary>
        public virtual string Id { get; set; }
        
        /// <summary>
        /// Version number that is automatically increased by NHibernate when the entity is updated.
        /// This property is used as a concurrency token to let NHibernate detect when an entity has been
        /// updated by another transaction after it was loaded into memory.
        /// </summary>
        public virtual int Version { get; set; }
        
        /// <summary>
        /// This timestamp is automatically filled by Cloud Spanner when a new row is inserted.
        /// </summary>
        public virtual DateTime CreatedAt { get; set; }
        /// <summary>
        /// This timestamp is automatically filled by Cloud Spanner when a row is updated.
        /// </summary>
        public virtual DateTime? LastUpdatedAt { get; set; }
    }

    public abstract class VersionedEntityMapping<T> : ClassMapping<T> where T : AbstractVersionedEntity
    {
        public VersionedEntityMapping()
        {
            Persister<SpannerSingleTableWithFixedValuesEntityPersister>();
            // DynamicUpdate(true) ensures that NHibernate will generate UPDATE statements that only modify the columns
            // of the table that have actually been updated.
            DynamicUpdate(true);
            
            // The UUIDHexGeneratorDef automatically generates and assigns a UUID as the primary key value of a new
            // entity. The value is not generated by Cloud Spanner.
            Id(x => x.Id, m => m.Generator(new UUIDHexGeneratorDef()));
            
            // Version properties are used by NHibernate to check that a record has not been updated by another
            // transaction after the record was loaded into the current session.
            Version(x => x.Version, m =>
            {
                // This indicates that the version number is never generated by the backend. Instead, the value is
                // determined client side by NHibernate.
                m.Generated(VersionGeneration.Never);
                // This ensures that a value is inserted into the version column when a new record is saved.
                m.Insert(true);
            });
            Property(x => x.CreatedAt, m =>
            {
                // The following prevents that NHibernate assigns a value to this property when the entity is inserted.
                // This might seem counter-intuitive, as we want this value to be filled during inserts. This is however
                // correct, as we don't want NHibernate to assign a value to the column in the INSERT statement, and
                // instead we want the value to be assigned its default value.
                m.Insert(false);
                // Cloud Spanner currently does not support default values for columns. This mapping is therefore
                // picked up by the SpannerEntityPersister, which will assign the value to the column when a new
                // record is inserted.
                m.Column(c => c.Default("PENDING_COMMIT_TIMESTAMP()"));
            });
            Property(x => x.LastUpdatedAt, m =>
            {
                // The following prevents that NHibernate assigns a value to this property when the entity is updated.
                // This might seem counter-intuitive, as we want this value to be modified during updates. This is
                // however correct, as we don't want NHibernate to assign a value to the column in the UPDATE statement,
                // and instead we want the value to be assigned its default value when it is updated.
                m.Update(false); 
                // Cloud Spanner currently does not support default values for columns. This mapping is therefore
                // picked up by the SpannerEntityPersister, which will assign the value to the column when a new
                // record is inserted.
                m.Column(c => c.Default("PENDING_COMMIT_TIMESTAMP()"));
            });
        }
    }
}
