// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using NHibernate.Mapping.ByCode;
using System;
using System.Collections.Generic;

namespace Google.Cloud.Spanner.NHibernate.Samples.SampleModel
{
    public class Singer : AbstractVersionedEntity
    {
        public virtual string FirstName { get; set; }
        public virtual string LastName { get; set; }

        /// <summary>
        /// FullName is a calculated column. It will always automatically be generated by Cloud Spanner and
        /// may not be included in any INSERT/UPDATE statement. NHibernate will issue an extra SELECT
        /// statement when a Singer instance is updated to get the most recent value of the column.
        /// </summary>
        public virtual string FullName { get; set; }

        /// <summary>
        /// DATE columns are best mapped to <see cref="SpannerDate"/>.
        /// This makes it easier to distinguish them from TIMESTAMP columns, which are mapped to <see cref="DateTime"/>.
        /// </summary>
        public virtual SpannerDate BirthDate { get; set; }
        public virtual byte[] Picture { get; set; }

        public virtual IList<Album> Albums { get; set; }
        public virtual IList<Concert> Concerts { get; set; }
        public virtual IList<Performance> Performances { get; set; }
    }

    public class SingerMapping : VersionedEntityMapping<Singer>
    {
        public SingerMapping()
        {
            Table("Singers");
            Property(x => x.FirstName);
            Property(x => x.LastName);
            Property(x => x.FullName, mapper => mapper.Generated(PropertyGeneration.Always));
            Property(x => x.BirthDate);
            Property(x => x.Picture);
            Bag(x => x.Albums, c => { }, r => r.OneToMany());
            Bag(x => x.Concerts, c => { }, r => r.OneToMany());
            Bag(x => x.Performances, c => { }, r => r.OneToMany());
        }
    }
}
