name: .NET Unit tests on Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Tests Connection
      working-directory: ./Google.Cloud.Spanner.Connection.Tests
      run: dotnet test --no-build --verbosity normal
    - name: Unit Tests NHibernate
      working-directory: ./Google.Cloud.Spanner.NHibernate.Tests
      run: dotnet test --no-build --verbosity normal
