name: .NET Integration Tests on Emulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests-on-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010
          - 9020:9020

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Unit Tests NHibernate
        # Also execute the unit tests with the SPANNER_EMULATOR_HOST env var enabled, to ensure that these tests do
        # not try to execute against the emulator.
        working-directory: ./Google.Cloud.Spanner.NHibernate.Tests
        run: dotnet test --no-build --verbosity normal
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
      - name: Integration Tests on Emulator
        working-directory: ./Google.Cloud.Spanner.NHibernate.IntegrationTests
        run: dotnet test --no-build --verbosity normal
        env:
          JOB_TYPE: test
          SPANNER_EMULATOR_HOST: localhost:9010
          TEST_PROJECT: emulator-test-project
          TEST_SPANNER_INSTANCE: test-instance
